{% set version="20170306" %}
{% set hash="68d747eb92061d642dcb9a064f1e8d89243637ac8648e520077671361a57752a" %}

package:
  name: cocacola
  version: {{ version }}

build:
  number: 0

source:
  fn: COCACOLA-python.zip
  sha256: {{ hash }}
  url: https://dl.dropboxusercontent.com/s/ciebt2y5h7pb9r2/COCACOLA-python.zip
  patches:
      - cocacola.patch

requirements:
  run:
    - fraggenescan
    - hmmer
    - perl
    - python <3
    - cvxopt
    - numpy
    - pandas
    - scipy
    - scikit-learn

test:
  source_files:
    - data
  commands:
    - cocacola.py -h
    - cocacola.py --contig_file data/SpeciesMock/input/SpeciesMock_Contigs_cutup_10K_nodup_filter_1K.fasta --abundance_profiles data/SpeciesMock/input/cov_inputtableR.tsv --composition_profiles data/SpeciesMock/input/kmer_4.csv --output data/SpeciesMock/result.csv

about:
  home: https://github.com/younglululu/COCACOLA
  license: GPL 3
  summary: COCACOLA - a general framework for binning contigs in metagenomic studies incorporating read COverage, CorrelAtion, sequence COmposition and paired-end read LinkAge
