{% set name = "MIPhy" %}
{% set version="0.9.2" %}
{% set hash="26bc9dd1a4a8cc074b197380cbd1284534df7d225ba4d3f53d389678b3d908e2" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

source:
  url: https://github.com/dave-the-scientist/{{ name | lower }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

requirements:
  build:
  - python >3
  - flask
  - numpy
  run:
  - python >3
  - flask
  - numpy

#test:
#  source_files:
#    - miphy_resources/tests
#  commands:
#    - miphy.py miphy_resources/tests/ugts_small.nwk miphy_resources/tests/ugts_info.txt

about:
  home: http://miphy.wasmuthlab.org/
  license: FreeBSD
  summary:  MIPhy is a tool to quantify phylogenetic instability in trees of multi-species gene families.